[package]
name = "drift"
version.workspace = true
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait = "0.1.81"
thiserror = "1.0.63"
tokio.workspace = true
tokio-util = "0.7.11"
tracing.workspace = true

[dev-dependencies]
tracing-test = "0.2.5"
